name: Build manager image

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ARM64
    steps:
      - run: |
          cd /home/neuvector/kyledong/build_test/manager

          cd manager
          make jar
          cd ..

          cp manager/Makefile .
          make manager_image
