name: Build fleet images

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ARM64
    steps:
      - run: |
          cd /home/neuvector/kyledong/build_test/neuvector

          cd neuvector
          make fleet
          cd ..

          cp neuvector/Makefile .
          cp neuvector/build/dockerignore .dockerignore
          make enf_image
          docker tag neuvector/enforcer:latest nvpublic/en:kdong
          docker login -u nvlab -p "${{ secrets.DOCKERHUB_NVBUILD_PASSWORD }}"
          docker push nvpublic/en:kdong
          docker logout
